spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: Manasi@123
    hikari:
      data-source-properties:
        stringtype: unspecified
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        maintainTimeStats: false
        maximum-pool-size: 5
        connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false

server:
  port: 9001
  error:
    include-message: always
